<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>
        
        /*const second = () => {
            setTimeout( () => {
                console.log('Async Hey there!');
            }, 2000 );            
        };
        
        const first = () => {
            console.log('Hey there');
            
            second();
            
            console.log('The end');
        };
        
        first();*/
        
        /*function getRecipe() {
            setTimeout( () => {
                const recipeID = [523, 883, 432, 974];
                
                setTimeout( (id) => {
                    const recipe = { 
                        title: 'Fresh tomato pasta',
                        publisher: 'Jonas'
                    };
                    console.log(`${id}: ${recipe.title}`);
                    
                    setTimeout( publisher => {
                        const recipe2 = { 
                            title: 'Italian Pizza',
                            publisher: 'Jonas'
                        };
                        console.log(recipe2);
                    }, 1500, recipe.publisher);
                    
                }, 1500, recipeID[2]);
                
            }, 1500)
        }
        
        getRecipe();*/
        
        // Same as above, but using ES6 Promises
        
        const getIds = new Promise( (resolve, reject) => {
            setTimeout( () => {
                resolve([523, 883, 432, 974] );
                // or reject([523, 883, 432, 974] ); in which case it will indicate to JS that the promise was rejected, and you can catch this later using the catch method
            }, 1000);
        } );
        
        const getRecipe = recID => {
            return new Promise( (resolve, reject) => {
                setTimeout( (id) => {
                    const recipe = { 
                        title: 'Fresh tomato pasta',
                        publisher: 'Jonas'
                    };
                    resolve(`${id}: ${recipe.title}`);
                }, 1500, recID);
            });
        };
        
        const getRelated = publisher => {
            return new Promise( (resolve, reject) => {
                setTimeout( pub => {
                    const recipe2 = { 
                        title: 'Italian Pizza',
                        publisher: 'Jonas'
                    };
                    resolve(`${pub}: ${recipe2.title}`);
                }, 1500, publisher);
            });
        };
        
        // IDs is the result produced by the resolve method if the promise is successful
        getIds
        .then( IDs => {
            console.log(IDs);
            return getRecipe(IDs[2]);
        })
        .then( recipe => {
            console.log(recipe); 
            return getRelated('Jonas');
        })
        .then( recipe => {
            console.log(recipe);
        })
        .catch( error => {
            console.log('Error');
            console.log(error);
        });
             
    </script>
</body>
</html>